### ISSUE TITLE
Should be able to change both `locale.allowed.list` and `default_locale`

### ISSUE THREAD

**Issue by brandones** [mekomsolutions/openmrs-module-initializer#159] opened 2021-11-10 16:18 UTC
I'm changing `locale.allowed.list` from `en,es` to `en,es_PE`; and simultaneously changing the `default_locale` to `es_PE`. This results in

```
Caused by: java.lang.IllegalStateException: An error occurred while loading from initializer
        at org.openmrs.module.pihcore.setup.InitializerSetup.loadPreConceptDomains(InitializerSetup.java:54)
        at org.openmrs.module.mirebalais.setup.ConfigurationSetup.configureNonConceptDependencies(ConfigurationSetup.java:175)
        at org.openmrs.module.mirebalais.MirebalaisHospitalActivator.started(MirebalaisHospitalActivator.java:59)
        ... 72 more
Caused by: org.openmrs.api.APIException: "es_PE" is not in allowed locales list
```

Presumably this is because the `default_locale` is being changed before the `locale.allowed.list`. However, if I reverse the order in the XML, I get

```
Caused by: java.lang.IllegalStateException: An error occurred while loading from initializer                                                               
        at org.openmrs.module.pihcore.setup.InitializerSetup.loadPreConceptDomains(InitializerSetup.java:54)                                               
        at org.openmrs.module.mirebalais.setup.ConfigurationSetup.configureNonConceptDependencies(ConfigurationSetup.java:175)                             
        at org.openmrs.module.mirebalais.MirebalaisHospitalActivator.started(MirebalaisHospitalActivator.java:59)                                          
        ... 6 more                                                                                                                                         
Caused by: org.openmrs.api.APIException: "es" can not be removed from allowed locales list because it is the default locale  
```

I think Initializer should handle these global properties specially, to always add and remove languages in the right order.

**Comment by mseaton** [comment] 2021-11-10 20:45
This is a tricky one - I'm not really sure we want to hard-code this into Iniz, as it is fundamentally an issue with core.  But if there is a quick win hack, that could work.

In the meantime @brandones , what about handling this issue specifically in manual way.  Manipulate the properties in the following order:

locale.allowed_list -> en,es,es_PE
default_locale -> es_PE
locale.allowed_list -> en,es_PE

Wouldn't that work?

**Comment by brandones** [comment] 2021-11-10 21:17
Maybe the proper solution is that core should expose a property setter function that allows setting multiple properties at once. Because I'm not sure it's right, either, to say that core should allow a situation where the default locale is not in the allowed locales list.

> Manipulate the properties in the following order

That does work, but can't be deployed reliably. To do that with Iniz you would need to deploy three separate revisions of `gp.xml` to all your servers. But yeah, doing that via the admin panel is the work-around.

**Comment by mseaton** [comment] 2021-11-10 21:31
@brandones why can't that be deployed reliably?  Is that due to the fact that gp.xml does not process GPs in order?  That would seem worth fixing if so.

**Comment by brandones** [comment] 2021-11-12 17:03
I mean that for an implementation like Mexico, where 20% of the servers are offline at any point in time, ensuring that three successive updates reach every server in the right order is very hard. But I was imagining that the ordered changes to properties would be represented by successive updates to `gp.xml`, and it seems like you're suggesting that the `gp.xml` file could contain the `locale.allowed_list` block twice?

**Comment by mseaton** [comment] 2021-11-12 18:07
> ensuring that three successive updates reach every server in the right order is very hard

You mean deploying multiple versions of the distro over time to achieve this??  No, I was definitely not suggesting that.

Yes, I'm suggesting that if gp.xml doesn't currently support setting the same property multiple times, in the order defined, this might be a way to support this.

**Comment by mseaton** [comment] 2021-11-15 17:15
@brandones I'm inclined to close this as Won't Fix, assuming a single gp.xml file that looks like this will work and do exactly what you want:

Assuming a starting state where locale.allowed_list = "en,es", and default_locale = "es", set 3 successive global properties as follows:

```
        <globalProperty>
            <property>locale.allowed.list</property>
            <value>en, es, es_PE</value>
        </globalProperty>
        <globalProperty>
            <property>default_locale</property>
            <value>es_PE</value>
        </globalProperty>
        <globalProperty>
            <property>locale.allowed.list</property>
            <value>en, es_PE</value>
        </globalProperty>
```

Can you confirm this works?  If so I think we should close this issue out.

**Comment by brandones** [comment] 2021-11-17 19:52
@mogoodrich confirmed in https://github.com/PIH/openmrs-config-ses/pull/49 . I don't love that the initial GP set is just needed for legacy support (I think the dream is that Initializer should be declarative), but it works.

**Comment by mseaton** [comment] 2023-01-04 12:42
@mks-d I'm inclined to close this out as Won't Fix, and address it in core if we feel that this should be better supported.  See comments above.  I'll leave it up to you.

**Comment by Ruhanga** [comment] 2023-03-27 09:20
Closing this issue as wont fix. Thanks for having confirmed this @mseaton.

**Closed by Ruhanga** 2023-03-27 09:20 UTC
